### PR TITLE
fixes maybstd imports for no_std on thumbv6m-none-eabi

### PR DESCRIPTION
**Pull request by sunny-g**
I'm having a tiny bit of trouble getting my Cargo workspace to completely work with patches, paths, a 0.0.0 version for this library and a few other build dep things, but I think this fixes the inability to use `borsh` in `no_std` b/c a failure to `use alloc::sync` on line 32. 

The remainder of the changes are just in keeping with the rest of the codebase, which only depends on `rc` and `sync` when `cfg(feature = "rc")`

### CODE REVIEW

**Comment by austinabell** [comment]
`alloc::sync` does exist, so not sure what could be the issue there, but I did notice that `rc` was broken when used without `std` feature. I fixed that specific problem with #88. Were you using this with std feature not set and rc set? If not, can you produce a repro of this error or more details?

**Comment by sunny-g** [comment]
Hmmm, this could be unique to my env. I'm currently blocked just adding `borsh` as a dependency to the sample Ledger Nano S [rust app](https://github.com/LedgerHQ/rust-app).

Cargo.toml (simplified):
```
[dependencies]
borsh = { version = "0.9", default-features = false }
nanos_sdk = { git = "https://github.com/LedgerHQ/ledger-nanos-sdk" }
nanos_ui = { git = "https://github.com/LedgerHQ/ledger-nanos-ui" }
```

and this is the error produced: 
```
> cargo build
    Updating crates.io index
   Compiling borsh-derive-internal v0.9.3
   Compiling borsh-schema-derive-internal v0.9.3
   Compiling borsh-derive v0.9.3
   Compiling borsh v0.9.3
error[E0432]: unresolved import `alloc::sync`
  --> /home/sunnyg/.cargo/registry/src/github.com-1ecc6299db9ec823/borsh-0.9.3/src/lib.rs:32:56
   |
32 |     pub use alloc::{borrow, boxed, format, rc, string, sync, vec};
   |                                                        ^^^^ no `sync` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `borsh` due to previous error
```

**Comment by sunny-g** [comment]
But to answer your questions, as you can see above I've disabled all features, under the assumption that you couldn't use `rc` without `std`. If that's the fix, then my bad!

**Comment by sunny-g** [comment]
So that's not the fix - I'm getting substantially more errors, including the aforementioned one. The target is `thumbv6m-none-eabi` - is that the culprit? I'm not too familiar with embedded rust.

**Comment by austinabell** [comment]
> So that's not the fix - I'm getting substantially more errors, including the aforementioned one. The target is `thumbv6m-none-eabi` with a recent nightly toolchain - could that be the culprit? I'm not too familiar with embedded rust.

Hmm, yeah so this is just a target-specific issue. I think support for this can be added, but I don't personally know the cleanest way to exclude `Arc` things just for this family of architectures. Also not sure if we are open to very specific configurations in this repo, we can open an issue but you might want to just fork where you remove the incompatible parts as a stopgap solution for now.

**Comment by austinabell** [comment]
> * where they're `exported` in `maybestd`, they aren't behind any flag, which (at least for me) was unexpected. Put another way, `feature = "std"` seems "broken" if `rc`'s feature-gates are ignored by the `std/no_std`.
> 
> So with respect to the users of `borsh::maybestd`, I do understand this as a breaking change, but with regards to the actual usage of the library, this change doesn't seem to break anything (though correct me if I'm wrong, I might be missing something).

Ack that this is probably correct, but I'm just being cautious since I'm not sure of all cases the lib is used. cc @matklad @frol any objections to putting `rc` and `sync` behind the `rc` feature flag?

**Comment by frol** [comment]
> any objections to putting rc and sync behind the rc feature flag?

No objections

**Review by austinabell — APPROVED** [review]
If no objections for a breaking change and this doesn't come with a patch release

**Review by frol — APPROVED** [review]
